### ISSUE TITLE
Можно выделить функцию для генерации числа в диапазоне

### ISSUE THREAD

**Issue by AlphaBeth** [kito4/itmo#3]
https://github.com/kito4/itmo/blob/df2a022e0696ded5bca452051523b6cb1713e689/LAB1/src/Main.java#L33

Если правильно назвать функцию и её аргументы, то комментарии не будут нужны.

**Comment by kito4** [comment]
public static float random_double(){
        return ((float) (Math.random() * 5) - 3);
